@startuml

!pragma layout smetana
!define STDLIB https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master
!include STDLIB/awslib/AWSCommon.puml
!include STDLIB/awslib/AWSSimplified.puml
!include STDLIB/awslib/General/all.puml
!include STDLIB/awslib/GroupIcons/all.puml
!include STDLIB/awslib/Storage/all.puml
!include STDLIB/awslib/Analytics/all.puml
!include STDLIB/awslib/Compute/all.puml
!include <tupadr3/common>
!include STDLIB/office/Users/csv_file.puml

sprite $powerBI img/powerbi-logo.png
AWSEntityColoring(powerBI)
AWSEntityColoring(csv)
AWSEntityColoring(subnetPublic)

skinparam linetype polyline

skinparam rectangle {
    BorderColor<<az>> #397DB5
    BorderColor<<subnetPublic>> #44852C
    BorderColor<<vpc>> #44852C
    BorderStyle<<az>> dashed
    BorderThickness<<az>> 2.0
    RoundCorner<<subnetPublic>> 25
    RoundCorner<<vpc>> 25
    Shadowing<<az>> false
    Shadowing<<subnetPublic>> false
    Shadowing<<vpc>> false
    DefaultTextAlignment<<subnetPublic>> right
}


rectangle powerBI <<powerBI>> as "<$powerBI{scale=0.07}>\n\n==Power BI"
User(dataAnalyst, "Data Analyst", "")
rectangle awscloud <<awscloud>> as "<color:AWS_COLOR><$Cloudalt></color>" {

    rectangle vpc <<vpc>> as "<$VirtualPrivateCloudVPC{scale=0.5,color=#3F8624}> 10.0.0.0/16" {
     rectangle az <<az>> as "eu-west-1a" {
        Redshift(redshift, "Redshift", "")
        SimpleStorageService(s3, "S3 ", "")
        KinesisFirehose(kinesisFirehose, "Kinesis Firehose", "")
        rectangle subnetPublic <<subnetPublic>> as "<size:15><$VPCSubnetPublic{scale=0.5,color=#3F8624}></size> Subnet Public 10.0.0.0/24" {
           EC2(ec2, "EC2", "")

        }
      }
    }
}

dataAnalyst -r-> powerBI : Analyze
redshift -l-> powerBI
ec2 --> kinesisFirehose
kinesisFirehose <- subnetPublic
kinesisFirehose -l-> s3
s3 -l-> redshift

@enduml