name: sparkci

on: [ push, pull_request ]

jobs:

  ansible:
    name: Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies
        run: cd modules/ansible && pip3 install molecule[docker] yamllint ansible-lint ansible
      - name: Run Molecule tests
        run: |
          cd modules/ansible/roles/bastion && molecule test && \
          cd ../spark && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  data-lake:
    name: Data Lake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up JDK 15.0.1
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Run cdktf
        run: |
          yarn --cwd modules/cdktf/ install && \
          yarn --cwd modules/cdktf/ fetch && \
          sbt "cdktf/runMain io.github.mvillafuertem.spark.cdktf.bastion.CdktfApp" && \
          cat modules/cdktf/src/main/resources/stacks/cdktf-stack/cdk.tf.json && \
          cat modules/cdktf/src/main/resources/stacks/cdktf-state/cdk.tf.json
          sbt "data-lake/runMain io.github.mvillafuertem.data.lake.SimpleDataLake" && \
          cat modules/data-lake/src/main/resources/stacks/simple-data-lake/cdk.tf.json
          sbt "data-lake/runMain io.github.mvillafuertem.data.lake.SimpleDataLakeUsingAWSLakeFormation" && \
          cat modules/data-lake/src/main/resources/stacks/simple-data-lake-using-aws-lake-formation/cdk.tf.json

  data-warehouse:
    name: Data Warehouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up JDK 15.0.1
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Run cdktf
        run: echo "Data Warehouse"